version: '3'

services:
  mongo_storage:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db

  redis:
    image: redis:7.0.0-alpine
    volumes:
      - redis:/data

  rabbit:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    depends_on:
      - mongo_storage
    environment:
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - EVENTHUB_TYPE=rabbit
      - RABBIT_CONNECTION=${RABBIT_CONNECTION}

  content:
    image: ghcr.io/ghosts-network/content:latest
    depends_on:
      - mongo_storage
    environment:
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - EVENTHUB_TYPE=rabbit
      - RABBIT_CONNECTION=${RABBIT_CONNECTION}

  news_feed:
    image: ghcr.io/ghosts-network/news-feed:latest
    command: "--server.enable --listener.enable"
    depends_on:
      - profiles
      - content
    environment:
      - MONGO_CONNECTION=${NEWS_MONGO_CONNECTION}
      - PROFILES_ADDRESS=http://profiles
      - CONTENT_ADDRESS=http://content
      - EVENTHUB_TYPE=rabbit
      - RABBIT_CONNECTION=${RABBIT_CONNECTION}

  account:
    image: ghcr.io/ghosts-network/account:latest
    ports:
      - "6620:80"
    depends_on:
      - mongo_storage
      - profiles
    environment:
      - ALLOWED_HOSTS=http://localhost:4200
      - ISSUER_URI=http://account
      - OAUTH_CLIENTS_SOURCE=file
      - SINGING_TYPE=Developer
      - MONGO_ADDRESS=${MONGO_CONNECTION}
      - PROFILES_ADDRESS=http://profiles
      - DEFAULT_CLIENT=angular_spa
      - EMAIL_SENDER=NULL
    volumes:
      - ${PWD}/clients.json:/app/clients.json

  gateway:
    image: ghcr.io/ghosts-network/gateway:latest
    ports:
      - "6610:80"
    depends_on:
      - content
      - account
      - profiles
      - news_feed
    environment:
      - ALLOWED_HOSTS=http://localhost:4200
      - AUTHORITY=http://account
      - AUTHORITY_REQUIRE_HTTPS=false
      - CONTENT_ADDRESS=http://content
      - PROFILES_ADDRESS=http://profiles
      - NEWSFEED_ADDRESS=http://news_feed
      - FILE_STORAGE_TYPE=local
      - ENABLE_PERSONALIZED_NEWSFEED=true

  spa:
    image: ghcr.io/ghosts-network/spa:latest
    ports:
      - "4200:80"
    depends_on:
      - gateway
      - account
    volumes:
      - ${PWD}/spa.config:/usr/share/nginx/html/config/config.js

volumes:
  mongo:
  redis:
